version: '3.3'

services:
  download:
    image: 192.168.1.16:5000/sd-download:2023.07.06
    volumes:
      - /mnt/user/appdata/sd-auto/data:/data

  auto:
    ports:
      - "7860:7860"
    volumes:
      - /mnt/user/appdata/sd-auto/data:/data
      - /mnt/user/data/ai/sd-outputs:/output
    image: 192.168.1.16:5000/sd-auto:2023.07.06
    environment:
      - CLI_ARGS=--allow-code --medvram --xformers --enable-insecure-extension-access --api